### ISSUE TITLE
[Feature Request] Include Move/Upgrade/Remove system-apps for root users

### ISSUE THREAD

**Issue by alecuba16** [d4rken-org/sdmaid#1342]
Would be a nice feature to include, is the only thing that is missing to be a complete system app manager, maybe for pro/paid users, I would pay for it for sure.

Check-out systemcleanup that implements this management for root users.

**Comment by mynewboat** [comment]
Good

**Comment by d4rken** [comment]
Can you elaborate what "Move" and "Upgrade" would do?

**Comment by alecuba16** [comment]
Move User app As System app: mv /data/app/myapp/*-> /system/app/myapp
Move User app As System Priv app (System app with lots of privilegies): mv /data/app/myapp/*-> /system/priv-app/myapp

Update System app: app exists on /data/app and /system/app with same com.myapp.main but the ones on /data/app is newer ,the same applies to System priv app (autodetecting the path)

Move System app As User app: mv /system/app/myapp/* or /system/priv-app/myapp/*  -> /data/app/myapp 

The last option is useful for debloat roms. You can check this described options in app called "systemcleanup" on "App" tab , and also on system app mover on playstore.

**Comment by SuperSandro2000** [comment]
I think this is out of scope for SD Maid and fits more into a root tool box.

**Comment by Y-T-G** [comment]
Will this feature be added?

**Comment by SuperSandro2000** [comment]
There is only one problem: System apps at least on samsung roms are in a "codename" folder that is most of the times totally different from the package name. How do you want to handle this? And moving apps to system especially different versions than currently installed can cause a lot of problems under magisk (eg mapping issues so ressource strings are missmatched). Then you need to reflash your rom and clear cache or this package name is not usable anymore. How do you plan to handle rom updates that include a previously user app under system if the user moved the app under system? You would break that app cause you have two folders under system with the same package name. I would suggest top leave this feature out because it will only cause headaches. If an advanced user wants to move an app he is more than capable to do that with an root file explorer or the terminal.
