### ISSUE TITLE
[Suggestion] fstrim

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#18]
Originally reported by: **Robert Callahan (Bitbucket: [CallahAndroid](http://bitbucket.org/CallahAndroid), GitHub: [CallahAndroid](http://github.com/CallahAndroid))**

---

It would be nice to incorporate the "fstrim" command as part of the function of SDMaid, it would save users from using another app for it?

---
- Bitbucket: https://bitbucket.org/d4rken/sd-maid/issue/18

**Comment by d4rken** [comment]
https://forum.xda-developers.com/showthread.php?t=2104326&highlight=brickbug

https://forum.xda-developers.com/android/software-hacking/project-brickbug-aftermath-recovering-t2823051

https://forum.xda-developers.com/android/apps-games/app-autotrim-t2963334

https://forum.xda-developers.com/showthread.php?t=1693704

https://forum.xda-developers.com/showthread.php?t=1644364

https://forum.xda-developers.com/showpost.php?p=31124285&postcount=785

**Comment by d4rken** [comment]
Implementing this would now be possible through Scheduler & MiscWorker (where the reboot task gets executed). An implementation would have to deal with this "brickbug" issue though, for the users safety.

**Comment by marksjc** [comment]
Comment from user:  I've been using Trimmer for about a year. That tool Trimmer Ver 1.34 by  "FiFtHeLEmEnT"  (case correctness not reliable).  It's very minimalist, and have System set to RW, it cleans that, at well.  Very fast and has never caused any problem (nearly a miracle for me).  

Here is the one page description from the app.  I would have attached but don't know how,  Feel free to delete (or so me to) if tmi/junk.

I don't want to edit Devs material, since it's their property. 

>>Trimmer is a user-friendly implementation of fstrim Linux utility.

Almost all Android devices use NAND chips for data storage. Because of how NAND chips work, they may become significantly slow after some time. Trimming would help to restore NAND Chips performance to their initial value. Although Android 4.3+ supports trim natively, users have no control over this process and Android doesnt trim the storage as much as it is supposed to do, which results in slow storage performance and thus laggy devies. Trimmer enables you to trim your device manually if you feel it has become laggy.

Trimmer incorporates a well-known fstrim utility which is a part of Linux kernel tools. This utility trims memory devices which support TRIM operation.

This application is free and ad-free, Please consider rating it 5 stars if it helped you :) <<

**Comment by d4rken** [comment]
```BASH
#!/system/bin/sh
 
TRIM_LOGFILE="/data/fstrim.log"
 
if [ -f $TRIM_LOGFILE ]; then
  mv $TRIM_LOGFILE $TRIM_LOGFILE.2;
fi
 
echo $(date) >> $TRIM_LOGFILE
 
#fstrim
fstrim -v /cache | tee -a $TRIM_LOGFILE;
fstrim -v /data | tee -a $TRIM_LOGFILE;
fstrim -v /system | tee -a $TRIM_LOGFILE;
```

**Comment by d4rken** [comment]
> You can run the following commands in a terminal emulator w/ sudo: fstrim -v /cache | fstrim -v /data | fstrim -v /system

**Comment by dragonGod97677** [comment]
Is SD Maid have a fstrim function?
