### ISSUE TITLE
Configure notifications and battery settings via AppControl

### ISSUE THREAD

**Issue by evandroks** [d4rken-org/sdmaid#2276]
Show all "turned on" Android App's Notification

I am a Sd Maid Pro user.

I have a Motorola Z2 Play with Android 8.0.0

1- Android says that some apps are active / using battery - Stay Focused and IFTTT
(Apps running in background)
But when I open SD Maid Pro it tells me that just SdMaid is running !!

2-I discovered that my battery is drained very fast when I have apps with Android Notification turned on.

(So ​​I decided to turn off app notification in most apps)

I would suggest a new function to be created in Sd Maid to resolve something that does not exist in the Android configuration menu.

On Android, in the Config (setup) menu, there is an option "Apps and Notifications", Notifications.

It says that on my device I have notifications turned off in 501 applications.

Is correct.
 But Android does not show a filter with just the list of apps where notifications are turned on.

In notifications I have to go into each application to see if the notification is enabled and then disable it.

(Some Android devices show the notification status (on / off) next to each app, but on my device and in several others it does not appear)

I've attached a screenshot from the Notification menu on my Android.

Please allow Sd Maid Pro to control application notifications and reduce the battery drain. 

Disabling notifications via SD Maid might be difficult, at least without root, I think...
But just filtering for on/off notifications will help me

**Comment by Yantis0m** [comment]
I feel like the "running" apps issue was kind of glazed over a bit. I am having this same issue, only SD Maid is shown as running. 

Otherwise I love this app! Cant wait till this is fixed so I can upgrade to Pro!

*App Info:

SD Maid 4.12.3
Free Version

*System Info:

Android 8.1.0 / Oreo / API 27
Baseband Version: MPSS.TA.2.3.c11-00065-8953_GEN_PACK-1.167126.1.182793.1
Build Number: OPM1.171019.019
Linux Kernel Version: 3.18.71-perf+
Http User Agent: Dalvik/2.1.0 (Linux; U; Android 8.1.0; LM-Q710(FGN) Build/OPM1.171019.019)

**Comment by d4rken** [comment]
@Yantis0m This ticket is about notifications. For running apps detection see #946
