### ISSUE TITLE
Application Cleanup Bug - Applications after clean do not close.

### ISSUE THREAD

**Issue by GabrielMGitHub** [d4rken-org/sdmaid#2686]
The new update came with a bug when clearing the applications cache, the application information windows are open after cleaning.
Note, since I had few applications to clean, only one window was left open, I had a previous test and several windows were left open.

![Screenshot_20190609-115942_SD Maid](https://user-images.githubusercontent.com/8754997/59160699-561a8800-8aaf-11e9-9402-55458a0ac4fc.jpg)
![Screenshot_20190609-120005_SD Maid](https://user-images.githubusercontent.com/8754997/59160703-5f0b5980-8aaf-11e9-8cfc-a7a7bbacb28d.jpg)
![Screenshot_20190609-120041_SD Maid](https://user-images.githubusercontent.com/8754997/59160710-67fc2b00-8aaf-11e9-8c31-980ba62c29c2.jpg)
![Screenshot_20190609-120046_Settings](https://user-images.githubusercontent.com/8754997/59160718-72b6c000-8aaf-11e9-9823-84fc62dc89b9.jpg)
![Screenshot_20190609-120050_Settings](https://user-images.githubusercontent.com/8754997/59160721-78140a80-8aaf-11e9-8fd0-1d87b0b4d475.jpg)

[sdmaid_logfile_1560092374904.zip](https://github.com/d4rken/sdmaid-public/files/3269665/sdmaid_logfile_1560092374904.zip)

**Comment by d4rken** [comment]
Not new in the update, basically happens since the addition of this feature.

Tough nut to fix. Doesn't happen on all ROMs/Launchers and preventing this has quite the high cost. The solution is difficult to code and bug prone. It will also slow down each app clearing by ~1-2 seconds.
SD Maid would have to start a screen in between that SD Maid can then close to tear down the previous screens above it.

I'm still looking for a better solution.

**Comment by GabrielMGitHub** [comment]
I've never had this problem, happened now with today's update, possibly error in your code.

**Comment by d4rken** [comment]
SD Maid SE should no longer have this issue.
