### ISSUE TITLE
App covered by notch in landscape mode.

### ISSUE THREAD

**Issue by sp1cyf0x** [d4rken-org/sdmaid#2725]
The right side of the app is covered by the notch when the action chooser is expanded, please adjust it so it could work correctly in landscape mode.
I'm using Samsung Galaxy A70, 6.7 inches, 20:9 ratio.
![Screenshot_20190618-151405_SD Maid](https://user-images.githubusercontent.com/24849056/59664895-1a34a080-91dc-11e9-8215-ba21e8e773b3.jpg)
![Screenshot_20190618-151420_SD Maid](https://user-images.githubusercontent.com/24849056/59664914-20c31800-91dc-11e9-9f2a-1c6ad7bd4333.jpg)

**Comment by d4rken** [comment]
I've got a Nokia 8.1 here which has a notch and I can't reproduce it. Also can't reproduce it on a Pixel3 emulator.

Does the Galaxy A70 have special display modes? By default only a fullscreen app should expand past the notch?

![2019-07-07 22 15 46](https://user-images.githubusercontent.com/1439229/60773405-8fbdcd80-a105-11e9-901b-abeed6eeef0b.jpg)

**Comment by spicyfoxx** [comment]
> I've got a Nokia 8.1 here which has a notch and I can't reproduce it. Also can't reproduce it on a Pixel3 emulator.
> 
> Does the Galaxy A70 have special display modes? By default only a fullscreen app should expand past the notch?
> 
> ![2019-07-07 22 15 46](https://user-images.githubusercontent.com/1439229/60773405-8fbdcd80-a105-11e9-901b-abeed6eeef0b.jpg)

It's true that the app only be covered by the notch in Full screen mode. In Auto mode it wouldn't (replaced by a black bar). But every others app I have doesn't be covered notch in Full screen, like the Discord app I showed is in Full screen mode, but the part covered by the notch is grey, not black. This isn't a serious problem, I just wanted it to be more useable on Full screen mode :P

**Comment by JeffHorinzon** [comment]
For aesthetic reasons, I think it would be cool to ONLY have the UI shifted but fill the notched area to make it looked nicer under fullscreen environment.  For darken's reference, I also have a screenshot that is reproduced through "forced" [Fullscreen mode] on a Galaxy S10 (Global/Exynos).
![Screenshot_20190720-235746_SD Maid](https://user-images.githubusercontent.com/3746534/61580949-99eebb80-ab4a-11e9-8713-ad25449e9c80.jpg)
(The black spot is where my camera's located at, it was only black because my third party battery indicator app filled that area black, but you get the idea :D)
