### ISSUE TITLE
if scheduled event is missed (because the device was shut down), maybe you should fire it on next app launch?

### ISSUE THREAD

**Issue by patrickdrd** [d4rken-org/sdmaid#3082]
my suggestion is that
if scheduled event is missed (because the device was shut down), 
you should fire it on next app launch

**Comment by d4rken** [comment]
Difficult without requiring major changes. We don't want to launch it very soon after reboot as it will have a huge impact on the device which may be bogged down by other apps doing stuff after reboot.

I'll have to check the current pattern again, I think normal misses, e.g. due to device sleep should be retried automatically, not sure if the device being powered down is an edge case here.
