### ISSUE TITLE
Support for navigation via cursor (e.g. tv remote)

### ISSUE THREAD

**Issue by d4rken** [d4rken-org/sdmaid#342]
Currently the layout and UI was not developed with cursor navigation in mind.
To fix this we would have to identify what prevents navigation with a cursor from working correctly:
- Focus order of items
- Child views that unnecessarily focusable
- tbd

Example setups:
https://cloud.githubusercontent.com/assets/1439229/14229593/8363f498-f937-11e5-8e01-c722c865fbe4.jpg
https://cloud.githubusercontent.com/assets/1439229/14229594/8366743e-f937-11e5-9982-f7cda00216e1.jpg

**Comment by challenges90** [comment]
Could you please add native support for Android TV? Ｉｔ＇ｓ ｓｏ ｃｕｔｅ ａｎｄ ｐｏｗｅｒｆｕｌ． Ｉ ｗａｎｔ ｔｏ ｗａｔｃｈ ｉｔ ｏｎ ｍｙ ＴＶ！

**Comment by d4rken** [comment]
I've never dealt with Android TV but I'll look into it at some point.

**Comment by d4rken** [comment]
Settings don't allow keyboard navigation.
https://cloud.githubusercontent.com/assets/1439229/14234381/55c31568-f9e2-11e5-8c60-62f7d9f63cdc.jpg

**Comment by bgiesing** [comment]
@d4rken I sideloaded on Android TV and it definitely needs this (otherwise we need to use a OTG or Bluetooth mouse which not everybody has)

**Comment by d4rken** [comment]
Main drawer should work since 4.1.3.
I know that settings doesn't allow keyboard navigation, what else?

**Comment by bgiesing** [comment]
Ah well since it's not in the Play Store on ATV, I haven't updated it since the 2nd or 3rd beta so let me go do that.

Not really much else that I can tell. It's more of just hard to navigate without a Leanback UX

**Comment by DJayM** [comment]
Some usefull info you asked me to post here so it dont get lost
 
Its a bit tricky anything in the settings doesn't have a visual indicator so I can't see what I'm selecting as an example let's say I wanna select explorer the easiest way to do it is to immediately press up on the remote this selects the 1st action on the toolbar (which does have a visual indicator) and from there I just count down 4 button clicks to get to explorer 4 because the settings titles get selected azwell. This only applys to the main settings screen though if I open any one of the settings category's like general settings or help I can see what I'm selecting because there's a visual indicator (grey highlight) so I can toggle check boxes and all that good stuff.

No fab buttons work but I think you knew/expected that already that's why the main action is in the toolbar azwell.

Some feedback.

**Quick access**

Its all good but when I select the scan button there's no visual indication its selected/highlighted but it is clickable so no problem with that really and I cant click the i icon to get information after running the scan.

**Explorer**

Will test later but I'm expecting this not to work well I never used it before though tbh so it's cool.

**Searcher**

All good but again can't click the i icon.

**App Control**

Can't do anything here except check and search if i click any app I can't expand the spinners or select any of the other items like run now kill application etc.

**Corpse finder**

Again works fine but can't press the I icon 

**System Cleaner**

All good but can't click the I icon all of the switches work ok in the filter manager and theres a visual indicator on all list items.

**App Cleaner**

All good but can't click the i icon.

**Duplicates**

Dunno wasn't any

**Biggest**

All good but can't navigate backwards after clicking on a item.

**Databases**

All good but can't click the I icon 

**Last Modified**

All good but can't click the I icon 

**Scheduler**

All good but if I select the seekbar I can't reselect the time picker unless I cancel and start again.

**Exclusions**

Dunno never used it.

**Statistics**

All good I can browse history click items on the tool bar only thing I can't do is click on the graph

I'm surprised how usable it actually is nice one its a shame it doesn't meet the tv store requirements or you could probably get it on there azwell👍 

This is officially the longest post I've ever written on G+ hopefully its usefull lol.﻿

Will do, just noticed if I select the last action on the toolbar and then press down it will highlight the i icon so ignore everything I said about that above^ :) I don't think there's anything wrong with the current entry highlights maybe just create your own for the Setting screen see 2nd from last post here http://stackoverflow.com/questions/18432966/change-selector-color-of-a-preference
