### ISSUE TITLE
Corpse finder deletes apps of other user accounts

### ISSUE THREAD

**Issue by Nek-12** [d4rken-org/sdmaid#3595]
The corpse finder app component deletes all the apps installed for other users but not installed for the main user ( user 0 ). It leaves the data untouched but deletes the apk files.
To reproduce this bug: 
1. Install sd maid for the root account.
2. Create another user account and install some apps that the main account doesn't have installed.
3. Go to SD maid and run the corpse finder. The apk files used by another account show up as corpses.
4. Running the cleaner destroys all the apps that that user had. If reinstalled, the data persists however.   
See screenshots for my set up and examples.  

Device: OnePlus 7pro   
Oxygen OS 10.3.3. Android 10 stock  
Rooted with Magisk 20.4  
SD Maid 4.15.12  
install-id: 4f18bef5-3a0c-42ca-9047-58587540e49a  

https://i.imgur.com/OLfqR8q.jpg  
https://i.imgur.com/LtDiK7i.jpg  
https://i.imgur.com/U3JXCeg.jpg  

Logs: 
[nse-6009885333849065169-sdmaid_logfile_1592205827202.txt.zip.zip](https://github.com/d4rken/sdmaid-public/files/4778655/nse-6009885333849065169-sdmaid_logfile_1592205827202.txt.zip.zip)  
Edit: Moved screenshots to imgur (they take a lot of space, not sure how to resize them on github), added proper info according to the "Reporting a bug" page.

**Comment by d4rken** [comment]
Thanks for the report. SD Maid does not work well in multii-user environments, it just didn't get a lot of love in that area due to being a rather rare use-case among SD Maid's user base.

SD Maid should look up all installed packages, independent of users, and this seems to not be supported/working correctly here.

The second user installs the extra apps. Is the scan with the false positive results being done on the second user or main/root user?

Can you record a debug log of the scan?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Nek-12** [comment]
I've updated the first comment, added the log you requested, @d4rken. The scan is being done on the primary user account (user 0).  
When the cleaner is run from the secondary account, it doesn't find any of the apps installed on the main account.

**Comment by d4rken** [comment]
This should be correctly handled in SD Maid 2 now.
