### ISSUE TITLE
It may be necessary to clean up empty folders in one pass

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3872]
Лучше сделать очистку пустых папок за один проход, без повторного сканирования. Clean Master очищает за один проход. Не совсем удобно при каждой очистке по нескольку раз делать повторное сканирование SystemCleaner. И многие плохо разбирающиеся пользователи не знают о такой необходимости, им проще не задумываться, сделать один раз сканирование и знать, что все очищено.

Нужно после полной очистки, включая AppCleaner и остальные фильтры 
SystemCleaner, сделать автоматическое повторное сканирование пустых папок с очисткой, и чтобы оно повторялось, пока пустых папок не останется. Повторное сканирование должно происходить только при включённом фильтре пустых папок.
Это также должно происходить после завершения очистки SystemCleaner, если она сделана без полной очистки.
 
Либо это должно происходить каждый раз только после очистки SystemCleaner, но тогда SystemCleaner должен быть последним в очереди.

Если просто усложнить способ поиска пустых папок, то не будут очищены папки, появившиеся после текущей очистки в SD Maid.

**Comment by razmanko** [comment]
https://github.com/d4rken/sdmaid-public/issues/3872#issue-687661288

**Comment by d4rken** [comment]
This should theoretically work, albeit in a limited scope, see #201.

Can you provide an example?

**Comment by Ingood5** [comment]
Почему в ограниченном объёме?

Уточните, какой именно пример, что именно не понятно.

**Comment by d4rken** [comment]
This should work for normal storage access, not external storage.

I think this should work for `/storage/emulated/0`, because I added a workaround for this.
I can't add a workaround for other storages (root or StorageAccessFramework), because that would require changing the system cleaner tool completely.

**Comment by Ingood5** [comment]
Вот пример.

Фильтр пустых папок нужно оставить в SystemCleaner, но сканирование и очистку вынести за пределы SystemCleaner и активировать в самом конце, после завершения очистки всеми остальными инструментами.

Либо нужно оставить в SystemCleaner, но он должен быть последним инструментом, а фильтр пустых папок последним в SystemCleaner, но при сканировании вместе с остальными инструментами и фильтрами SystemCleaner сканирование пустых папок не должно запускаться. Оно запустится позже, во время очистки.

Как фильтр должен работать:
1. Происходит сканирование пустых папок.
2. Пустые папки очищаются и SD Maid запоминает родительские каталоги удалённых папок.
3. Происходит проверка всех родительских каталогов, и все найденные пустые удаляются и опять помечаются для следующей проверки.
4. И так повторяется, пока пустых родительских каталогов не будет найдено.

**Comment by d4rken** [comment]
> Here's an example. The empty folder filter should be left in the SystemCleaner, but scanning and cleaning should be moved outside the SystemCleaner and activated at the very end, after all other tools have finished cleaning. Or it should be left in the SystemCleaner, but it should be the last tool, and the empty folder filter the last in the SystemCleaner, but when scanning along with the rest of the SystemCleaner tools and filters, the scan for empty folders should not start. It will start later during cleaning.

That might be possible, but I don't want to create depdencies between the different tools, it will make everything complicated.

> How the filter is supposed to work: Scanning empty folders. Empty folders are cleared and SD Maid remembers the parent directories of the remote folders. All parent directories are checked, and any empty ones found are removed and marked again for the next check. And so it repeats until empty parent directories are found.

That's not possible because of the way the SystemCleaner works. The SystemCleaner generateds a stream of data about all files and folders on the device, each Default (or user) filter registers for this stream and can then decide if the information matches the criteria.

This makes it easy to create multiple filters, especially self made filters by users, that can be exported & imported.
It does not allow for any more complex logic like remembering, or marking paths, or obtaining new information.  Each filter can only work with the information it is given by the SystemCleaner to all filters.

I added some "hacks" with  #201, but any further changes would require the SystemCleaner to be completely changed.

I understand that it's not perfect for empty directories, but empty directories don't have a huge negative impact on the device, so it does not warrant me spending so much time on completely changing everything. Huge changes to this are also problematic because users won't like it if their existing custom filters break in an update.

**Comment by Ingood5** [comment]
Возможно, я не совсем правильно выразился. Я имел ввиду создать отдельный механизм, который после очистки ищет пустые папки и очищает их по этой схеме:
> Empty folders are cleared and SD Maid remembers the parent directories of the remote folders. All parent directories are checked, and any empty ones found are removed and marked again for the next check. And so it repeats until empty parent directories are found.

Если он не соответствует задумке SD Maid, можно его сделать в виде опции в настройках и сделать по умолчанию отключенным. Тот, кому он нужен, всегда сможет его включить.

**Comment by d4rken** [comment]
I think I understood.

I think you underestimate how complicated it would be to add this **cleanly**.
I do not want to use "glue" and "duct-tape" to add this somewhere in SD Maid and increase the potential for bugs.

* Benefit of this feature = __LOW__ Empty directories do not take much space
* Cost of this feature = __HIGH__ It requires major changes to SD Maids task-based architecture.

:point_right: Low priority to work on this.

**Comment by Ingood5** [comment]
Вычислить все пустые папки заранее, чтобы очистить их за один проход, тоже не получится?

Или добавить в настройки активацию повторного запуска SystemCleaner после завершения очистки, с автоматической очисткой, пока пустые папки не закончатся.

**Comment by d4rken** [comment]
Everything is possible, but it needs to be done correctly, and that is not always quick or easy.

It's like adding a 5th wheel to a car, you can weld and glue a 5th wheel to a car with little time, but doing it correctly requires research and lots of time, because the car was designed to work with 4 wheels :grin: 
The system cleaner tool in SD Maid was not designed to have such logic.

I already don't have enough time for all of the things I want to improve in SD Maid, and this one will take a lot of time, and there is little benefit, not a good time investment :frowning_face: .

**Comment by Ingood5** [comment]
Насколько небезопасно удалять все пустые папки на устройстве? Я имею ввиду если создать свой фильтр для удаления всех пустых папок. Что именно может произойти? Можете привести примеры?

**Comment by Ingood5** [comment]
> Насколько небезопасно удалять все пустые папки на устройстве? Я имею ввиду если я создам свой фильтр для удаления всех пустых папок. Что именно может произойти?

Вы не пропустили?

**Comment by d4rken** [comment]
In most cases it is probably not dangerous. Some apps may misbehave if they are badly programmed and don't check if a directory exists before trying to use it. I think there was one issue with syncthing and empty folders? Can't remember the details right now :thinking: 

SD Maid excludes few empty directories in default filters (e.g. Android/data) to just save resources, as they will be recreated anyways.
