### ISSUE TITLE
Proposing changes to statistics

### ISSUE THREAD

**Issue by Ingood5** [d4rken-org/sdmaid#3997]
Статистика автоматически проматывается вверх, если зайти в любой пункт, а затем выйти назад.

> Remember scroll states when navigating between different lists in statistics.

[video.zip](https://github.com/d4rken/sdmaid-public/files/5268955/video.zip)

**Comment by Ingood5** [comment]
Что означает пункт "restored" в статистике? Он повторяется каждый день, часто по многу раз, хотя я не захожу в SD Maid. Написано, что он связан с расписанием. Он нужен пользователю?

**Comment by d4rken** [comment]
> Что означает пункт "restored" в статистике? Он повторяется каждый день, часто по многу раз, хотя я не захожу в SD Maid. Написано, что он связан с расписанием. Он нужен пользователю?

It means that when SD Maid was started and SD Maid checked the scheduler, it was noticed that the scheduler should be activated, but it was not.
This means that the scheduler was enabled in SD Maid, but there was no alarm set in the system that would start it, so SD Maid restored the scheduler countdown/alarm.

Normally this happens after reboots, because all alarms after removed and apps have to restore them.
