### ISSUE TITLE
Empty '.trashed' files option...

### ISSUE THREAD

**Issue by TheMysticS** [d4rken-org/sdmaid#4169]
On Android 11, if a file is deleted using a 3rd party app (and may be using stock apps too), it is actually hidden and not completely deleted. The OS deletes the file after 30 days, so a file that is accidentally deleted can be recovered within 30 days. While that is a great feature, it would have been nice if there was a simple provision to view 'trashed' files, so they can be recovered.

On OnePlus 8T, there is a hidden folder called '.oprecyclebin' that seems to be holding some (if not all) of the 'trashed' files. I also remember seeing a '$.Trash$' folder and I am not sure what that was for.

**Under System Cleaner tool - User tab, I added the following:

1. Trash - to delete all files whose names begin with '.trashed'.
2. OPRecycleBin - to delete all files in the PATH '/storage/emulated/0/.oprecyclebin'.
3. Recycle Bin - to delete all files in the PATH '/storage/emulated/0/.$Trash$'. - After running this, I no longer see the '$Trash$' hidden folder. I hope the OS would recreate this folder as and when required. And I don't know how this folder is different to the '.oprecyclebin' folder.**

Can you provide an easy and simple way to empty the recycle bin and remove all trashed files?

I don't understand the difference between BASEPATH, PATH CONTAINS & LOCATION. 
1. Aren't all these one and the same thing?
2. Can you allow us to access the folder through an explorer, instead of having to type the entire path?

Thanks.

**Comment by d4rken** [comment]
If you know specific apps that do this, it would be best to make them known to the AppCleaner, it's much smarter than the system cleaner. 
To do that I need the package names, full path of the folder, and content layout of the recycle bin folder (i.e. use explorer save directory structure).
I think the `.oprecyclebin` could be something for the AppCleaner. Is there a specific recycle bin app?

To add a new default filter to the system cleaner we first need to come up with common enough folder names to warrant this, that also only have a small chance of not being a recycle bin on some devices. `.trashed` may be such a candidate.

**Comment by Sridhar-Ananthanarayanan** [comment]
Here are some observations:

1. I still don't see the '.$Trash$' folder. I guess this is an Android 11 folder that should be available on all devices, irrespective of the OEM. Hopefully it should get regenerated by Android on my device whenever a need arises.

2. The '.oprecyclebin' should be a OnePlus specific folder. I have seen files in that folder that were deleted by SD Maid after I ran the user created System Cleaner option mentioned in the original post. It's location is here:
'/storage/emulated/0/.oprecyclebin'.
At the moment it is empty, and I am not sure how files end up being there. I tried deleting a few files using Google Photos, OnePlus Gallery app, OnePlus File Manager, etc, but this folder continues to remain empty, despite the files being deleted. The OnePlus file manager app seems to be permanently deleting the files, without moving them to the recycle bin, quite opposite to how Android 11 is supposed to work.

3. The '.trashed...' files are generated by Google Photos (and may be other apps too, but I haven't seen one yet). Whenever a delete a file using Google Photos, in Android 11, I get a prompt that to 'Allow' the file to be moved to trash. Once allowed, I find the file in my Google photos Trash bin in the library. At the same time, this file becomes hidden in my device because Google Photos renames the file with a prefix '.trashed-xxx' where xxx is some random number. Please note that this file continues to remain in the original location. It is NOT moved to the '.oprecyclebin' folder. I guess these will be deleted automatically by Android after 30 days. However, if I empty the trash in Google Photos library, this file is permanently deleted from the device. I do get a prompt when doing so in Google Photos that warns about permanently deleting the file.

4. Apps that provide a built in recycle bin feature - if a file is deleted using such apps, that file is moved from it's original location to the app's data folder which holds a sub-folder called 'recycle bin'. They don't appear in the '.oprecyclebin' folder.

5. The AppCleaner function of SD Maid - there is no option to create a user filter like it is available under System Cleaner. I didn't get what you mean when you say 'make them known to the AppCleaner'.

**Comment by d4rken** [comment]
> I still don't see the '.$Trash$' folder. I guess this is an Android 11 folder that should be available on all devices, irrespective of the OEM. Hopefully it should get regenerated by Android on my device whenever a need arises.

Don't see it on a Pixel5, i think it's OEM specific.

> The '.oprecyclebin' should be a OnePlus specific folder. I have seen files in that folder that were deleted by SD Maid after I ran the user created System Cleaner option mentioned in the original post. It's location is here:
'/storage/emulated/0/.oprecyclebin'.
At the moment it is empty, and I am not sure how files end up being there. I tried deleting a few files using Google Photos, OnePlus Gallery app, OnePlus File Manager, etc, but this folder continues to remain empty, despite the files being deleted. The OnePlus file manager app seems to be permanently deleting the files, without moving them to the recycle bin, quite opposite to how Android 11 is supposed to work.

AFAIK there is no recyclebin mechanic built into Android 11, so stuff being permanently deleted is what I would expect.

> The '.trashed...' files are generated by Google Photos (and may be other apps too, but I haven't seen one yet). Whenever a delete a file using Google Photos, in Android 11, I get a prompt that to 'Allow' the file to be moved to trash. Once allowed, I find the file in my Google photos Trash bin in the library. At the same time, this file becomes hidden in my device because Google Photos renames the file with a prefix '.trashed-xxx' where xxx is some random number. Please note that this file continues to remain in the original location. It is NOT moved to the '.oprecyclebin' folder. I guess these will be deleted automatically by Android after 30 days. However, if I empty the trash in Google Photos library, this file is permanently deleted from the device. I do get a prompt when doing so in Google Photos that warns about permanently deleting the file.

So we can attribute this folder to Google Photos, can you make a sepperate ticket for this with the exact path, content and packagename+version of your Google Photos? Then we can include that under the "recycle bins filter" in the AppCleaner.

> Apps that provide a built in recycle bin feature - if a file is deleted using such apps, that file is moved from it's original location to the app's data folder which holds a sub-folder called 'recycle bin'. They don't appear in the '.oprecyclebin' folder.

Same as above, if you make extra tickets with the necessary details on this, we can include this in SD Maid's recyclebin filter in AppCleaner.

> The AppCleaner function of SD Maid - there is no option to create a user filter like it is available under System Cleaner. I didn't get what you mean when you say 'make them known to the AppCleaner'.

Correct, that can only be changed in an update. I mean that we can include it if you create a ticket with the necessary details such that I can include it in an update :wink:

**Comment by Sridhar-Ananthanarayanan** [comment]
> > I still don't see the '.$Trash$' folder. I guess this is an Android 11 folder that should be available on all devices, irrespective of the OEM. Hopefully it should get regenerated by Android on my device whenever a need arises.
> 
> Don't see it on a Pixel5, i think it's OEM specific.

May be. I'll let you know if I see that folder again. But I am sure it was there before I deleted it with SD Maid.
> 
> > The '.oprecyclebin' should be a OnePlus specific folder. I have seen files in that folder that were deleted by SD Maid after I ran the user created System Cleaner option mentioned in the original post. It's location is here:
> > '/storage/emulated/0/.oprecyclebin'.
> > At the moment it is empty, and I am not sure how files end up being there. I tried deleting a few files using Google Photos, OnePlus Gallery app, OnePlus File Manager, etc, but this folder continues to remain empty, despite the files being deleted. The OnePlus file manager app seems to be permanently deleting the files, without moving them to the recycle bin, quite opposite to how Android 11 is supposed to work.
> 
> AFAIK there is no recyclebin mechanic built into Android 11, so stuff being permanently deleted is what I would expect.

Okay. I read a few online articles that spoke about it, so thought it may have been implemented. Here are some links for reference:

https://www.xda-developers.com/android-11-hidden-recycle-bin-trashed-photos-videos/

https://www.firstpost.com/tech/news-analysis/android-11-might-come-with-a-hidden-recycle-bin-feature-to-let-trash-files-instead-of-deleting-them-8493351.html

> 
> > The '.trashed...' files are generated by Google Photos (and may be other apps too, but I haven't seen one yet). Whenever a delete a file using Google Photos, in Android 11, I get a prompt that to 'Allow' the file to be moved to trash. Once allowed, I find the file in my Google photos Trash bin in the library. At the same time, this file becomes hidden in my device because Google Photos renames the file with a prefix '.trashed-xxx' where xxx is some random number. Please note that this file continues to remain in the original location. It is NOT moved to the '.oprecyclebin' folder. I guess these will be deleted automatically by Android after 30 days. However, if I empty the trash in Google Photos library, this file is permanently deleted from the device. I do get a prompt when doing so in Google Photos that warns about permanently deleting the file.
> 
> So we can attribute this folder to Google Photos, can you make a sepperate ticket for this with the exact path, content and packagename+version of your Google Photos? Then we can include that under the "recycle bins filter" in the AppCleaner.

As mentioned before, there is no separate folder created by Google Photos. Google Photos only renames all files that are deleted using the app with a prefix ".trashed-xxx" and the files continue to remain in their original locations. On the web, these files are moved to the Trash bin in the library. If I delete a file in the online bin using Google Photos, the local file (which is renamed with the prefix ".trashed-xxx") too gets deleted permanently. So the files aren't moved, only renamed and hidden in their original locations when first deleted. Upon deleting them again from the online bin, they get removed from the device permanently. You should be able to verify this on your Pixel 5. 
All that SD Maid needs to do, if the user configures it that way like I did, is to look for all files whose names begin with '.trashed-' and delete them to remove the files permanently.

Let me know if a ticket is still required for this.
> 
> > Apps that provide a built in recycle bin feature - if a file is deleted using such apps, that file is moved from it's original location to the app's data folder which holds a sub-folder called 'recycle bin'. They don't appear in the '.oprecyclebin' folder.
> 
> Same as above, if you make extra tickets with the necessary details on this, we can include this in SD Maid's recyclebin filter in AppCleaner.

When apps that provide an in-app recycle bin delete files, they move them to a separate folder within their own respective data folders which is in Android/ Data location, that is no longer accessible to 3rd party apps on Android 11, without root. I use F-Stop which is a Gallery app with recycle bin feature. I have checked and confirmed that files deleted using this app are found under /storage/emulated/0/Android/Data/com.fstop.photos/files/recycleBin. This location won't be accessible to SD Maid without root. I also see that the app renames the files when it moves to its recycle bin and there is no fixed pattern like it is in the case of Google Photos ('.trashed-xxx').
Again, let me know if a ticket is still required for this.
> 
> > The AppCleaner function of SD Maid - there is no option to create a user filter like it is available under System Cleaner. I didn't get what you mean when you say 'make them known to the AppCleaner'.
> 
> Correct, that can only be changed in an update. I mean that we can include it if you create a ticket with the necessary details such that I can include it in an update 😉

Here too, since the Android/data folder is inaccessible on Android 11, what exactly should I mention in a new ticket?
