### ISSUE TITLE
Bug: The searcher never finds anything!

### ISSUE THREAD

**Issue by COUPON4Vitamins** [d4rken-org/sdmaid#5617]
## What happened?
The searcher never finds the files I know are in my device!

### What did you expect to happen?
I expected to find WeChat, Tencent, TikTok and Musically files but always get 0 as result!

### How can I reproduce the issue?
I have both WeChat and TikTok installed and the searcher never finds these files!

### Comments
Why is Android 11 so buggy for SD Maid? I've never had so many issues on lower Android versions!
### SD Maid
Version: `5.4.0 (50400)`
Pro: `isPro=true || isComplete=true (unl=true, iap=false, acc=false)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `ZONKO/K118/K118:11/R01005/1632291878:user/release-keys`
#

**Comment by d4rken** [comment]
Please provide your search terms, and the path of the files that should have been found, and a debug log:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

This might be related to newer versions requiring access via the storage access framework. This isn't fully supported yet by the Searcher tool.

**Comment by COUPON4Vitamins** [comment]
Yes I guess it's that. The storage access framework! Damn why they did this? It says because of privacy reasons but this makes no sense that i can't find my own files! When aprox will there be a fix for it?

**Comment by d4rken** [comment]
Don't know yet, not trivial to add and will be slow as fuck, especially searching through files.
Getting tired of having to redo major code portions of SD Maid with every Android version, just because Google keeps moving the goalpost. 😠 
They should just slap a toggle on it and let users decide to keep old behavior.

**Comment by d4rken** [comment]
Still, SAF should only affect files under `/sdcard/Android/data` isn't WeChat/Tencent on `/sdcard/`?

**Comment by COUPON4Vitamins** [comment]
I just sent the bug reports to your email

**Comment by d4rken** [comment]
The second log just contained an AppCleaner scan as far as I could tell.

The first log was ok.

The log contains `grep -l 'tencent' '/storage/emulated/0/Pictures/WeChat'`. 
FYI: It does not make sense to search for "tencent" inside an image file, there will be no texts in an image, just image data. "Content search" is mostly useful for text files.

If I create a folder `/storage/emulated/0/tencent` and type `tencent` into the search name field, it is found.
The  folder `/storage/emulated/0/Pictures/WeChat` is empty.

I'm assuming they are not on the sdcard because the searcher data shows nothing pointing to that.

Can you please provide the path that the files are actually stored under? Your email said the SystemCleaner filter picked them up? What is the path?

**Comment by COUPON4Vitamins** [comment]
Yes the files are under Android/data. And "tencent" is just one exactly of the many files the searcher isn't able to find there. I just sent you a new log. My own filter can find this files. So I don't understand why the searcher can't! 🥲
![Screenshot_20220801-092034](https://user-images.githubusercontent.com/20388814/182157315-7242f930-e1b7-473b-b230-9fdd7479ea90.png)
![Screenshot_20220801-092034](https://user-images.githubusercontent.com/20388814/182157396-8652e2dc-bfc2-466c-9613-4a519fcd4b05.png)

**Comment by COUPON4Vitamins** [comment]
Oh sorry see twice the same pic, this should be the other: 
![Screenshot_20220801-091841](https://user-images.githubusercontent.com/20388814/182157824-964851a1-2d13-4da2-80a2-9e4eb002ea4d.png)

**Comment by d4rken** [comment]
>  So I don't understand why the searcher can't! 

Searcher and SystemCleaner use different mechanisms for searching.
The SystemCleaner search method does not support searching inside of files.

A cheap fix could be to use the SystemCleaner search method, and disable searching inside of files?

**Comment by COUPON4Vitamins** [comment]
Yes but using searcher would be more convenient
