### ISSUE TITLE
SD Maid Terminated from Play Store

### ISSUE THREAD

**Issue by BishopWolf** [d4rken-org/sdmaid#6098]
**Describe the bug**
SD Maid banned from Play Store

**To Reproduce**
no chance to download/install/recover purchases

**Expected behaviour**
SD Maid in Play Store

**Additional context**
[SD Maid Terminated from Play Store](https://www.androidpolice.com/sd-maid-terminated-play-store-stalkerware-policy/)

**Comment by Fede2782** [comment]
Is it possible to get back the money because I bought the Pro version and now I can't use it anymore.

**Comment by BishopWolf** [comment]
I hope google respond quickly, I love your apps

**Comment by Fede2782** [comment]
I hope so too. SD maid helped me a lot in these last 5 years when I had to use low-storage devices where I didn't have much space to save my data. SD Maid has been an amazing software for Android and I used it until yesterday for cleaning my S23. 🥹

**Comment by scorpion421** [comment]
https://www.gizmochina.com/2023/08/24/google-removing-cleaner-apps-from-the-play-store/
Suuuuure. Google being Google and removing one of the most well known apps doing just what they claim. SD Maid was the very first app I bought (0.50 Euro, thanks, Darken :D) back in 2011. Nov 13th 2011 to be exact and as soon as 2 came out: Bought. Why? Because I knew what I buy. But to be honest: If you don't pay Google to get on top like wonky CCleaner (Still on Google Play btw.) and the felt millions of other apps, just being Chinese spyware still on Google Play: The play store is basically dead. A toxic place for all the crap some people call an app. 

Darken: If you get your account back, please implement a key like you had. Remove SD Maid from Google and only leave the license there.

If I didn't have had purchased all apps back then when real devs were out to bring freedom and quality to Android, I can't imagine how hard it is to find legitimate apps nowadays. I'd say: Almost impossible. Close to recommend Apple and their Store, to be honest.

So thanks again, Darken, for all the work you did and hopefully will spend on SD Maid 2 in the future.

**Comment by t0n4** [comment]
All the apps disappear again.

**Comment by t0n4** [comment]
> Not just SD Maid. My whole account, all my apps.
> 
> I've filled an appeal, I don't yet know how to continue.

All apps disappeared again

**Comment by mrfoxie** [comment]
hey y dont u upload it on fdroid its open source

**Comment by KrareophKheseare** [comment]
And, google being google, they have zero problems with a thoeving copycat.
https://play.google.com/store/apps/details?id=com.mouhdimaidsistimcleantol.sdmiad

**Comment by scorpion421** [comment]
@KrareophKheseare I filed a report of impersonation here: https://support.google.com/googleplay/android-developer/contact/policy_violation_report
Yes, I'll fight for SD Maid too.

**Comment by scorpion421** [comment]
Not difficult. Impersonation is impersonation. Just if something got removed, it doesn't mean it isn't impersonation anymore :).

**Comment by SSlz** [comment]
I have the same problem with my purchased apps.

**Comment by BishopWolf** [comment]
![image](https://github.com/d4rken-org/sdmaid/assets/11816952/ca75ac54-15c5-4607-a5a3-e3a33d5b98e5)

**Comment by BishopWolf** [comment]
BTW, @d4rken. Please add SDMaid to F-Droid and add a way to recover our purchases (perhaps it exists now, but I'm probably blind).

**Comment by t0n4** [comment]
They back to Play Store, SD Maid Pro unlock is missing

**Comment by d4rken** [comment]
I'm closing this "bug" as fixed, with joy :beers:.

Thanks for all your support.

Sorry for my silence, it was a stressful time for me.

Google reinstated my account and all should be back.

> They back to Play Store, SD Maid Pro unlock is missing

Correct, for some reason it took longer than all others to be restored. :shrug: 

More technical details about the account restoration here if you are interested:
https://old.reddit.com/r/androiddev/comments/16e7gf4/and_on_the_19th_day_google_play_spoke_and/



> hey y dont u upload it on fdroid its open source

It's not as easy as "just uploading" there are requirements and the source code for SD Maid 1 is not ready, it would be a lot of extra refactoring work that I currently don't want to do.

SD Maid 2 is on f-droid (if you add Izzy's repo), work in progrses :+1:.

@KrareophKheseare Yeah that copycat thing was an unreal case of irony... Thanks for reporting it.
