### ISSUE TITLE
AppControl still showing deleted things

### ISSUE THREAD

**Issue by 1TAYAT1** [d4rken-org/sdmaid#6185]
I downloaded a theme on my Samsung S20 plus phone called "Space", I tried it and I did not like it and decided to delete it, the problem is when I delete it from the list of themes I decided to delete another app called VLC from SDMaid app via AppControl Service, And here's the problem that I found a long list of 77 files, when I try to delete them A message appears: (The app wasn't found in the list) It stays in the list of applications and is not deleted.

My request is either to fix the app so that I can delete the stubborn list or at least hide it

Thank you so much 

![Screenshot_20231126-122516_Package installer](https://github.com/d4rken-org/sdmaid/assets/29573436/ceb9366f-3026-48f0-a8bd-31916366b274)

**Comment by d4rken** [comment]
The themes on Samsung ROMs are a self-brewed Samsung thing and don't behave like "normal apps".
I'm not sure what the exact nature of the issue is here.

SD Maid 1 is in maintenance, if the same issue also occurs in SD Maid 2, consider opening a new issue ticket there and I'll look into it.

https://github.com/d4rken-org/sdmaid-se/issues

**Comment by 1TAYAT1** [comment]
No it doesn't occur in the sdmaid 2

But I am a big fan of sdmaid 1, and I use it with all my phones about 6
years ago.

Thank you

**Comment by 1TAYAT1** [comment]
Can u let exclusion manager of SDMaid2 import settings from SDMaid1

And also SystemCleaner as well
