### ISSUE TITLE
Clutterreport: /storage/F2D7-1A24/Android/data/com.pandora.android (FP)

### ISSUE THREAD

**Issue by Jetlyf114** [d4rken-org/sdmaid#6237]
### Target
Target: `/storage/F2D7-1A24/Android/data/com.pandora.android`
Prefix-free: `com.pandora.android`
Path-prefix: `/storage/F2D7-1A24/Android/data/`
Type: `DIRECTORY`
Location: `PUBLIC_DATA`
Current keeper state: `false`
Suggested keeper state: `false`

### Current owners
Appname: `?`
Packagename: `com.pandora.android`
Version: ` (-1)`

### SD Maid
Version: `5.6.3 (50603)`

### Device
Fingerprint: `motorola/maui_a/maui:12/S3SGS32.39-191-15/7fd94:user/release-keys`

### Comment
`this is a malware tracing my phone `

**Comment by Gallagherrita833** [comment]
What is a malware and what does it mean that it's tracing your phone? I'm asking because I've been receiving occasional notifications throughout my day, each day, that informs me that my phone is being traced followed by the option to share the trace or not so curious as anything, of course I attempted to share the traced files so I could hopefully open, view & figure it out... BUT, to my complete and utter disappointment, I'm unable to share the files because their size exceeds the maximum size I'm permitted to share on my device and I'm also unable to view/open either bc I apparently don't have appropriate software to view abd or open such a file. Very frustrating and very annoying! Does it for lack of better terms mean that my device is being hacked??? Please **HELP**!
