### ISSUE TITLE
ROM debloat function with saved batch for use after ROM update or fresh install

### ISSUE THREAD

**Issue by ryder203** [d4rken-org/sdmaid#865]
SD maid has an awesome function called "app control" which allows root users to even remove system apps. I use this feature on various ROMs - especially on MIUI ROMs on my Xiaomi device (much bloat) after flashing. My idea is, that users can have a function category which is called debloat batch or something like that, similiar to the app control function, but it is implmented only for system apps (apps or bloatware in /data optional). The removal process can be saved as a repeatable task.

- remove apps in /system/app and /system/priv-app plus the app data (optional) as batch
- save the removal task as batch (file on SD card or storage)
- Ability to share the batch tasks with other users (import/export)
- Ability to edit the batch tasks
- similiar UI concept as for "app control"
- Blacklist for important system apps which should not be allowed for removal (system stability)
- Hint for users regarding the risks and info to dirty flash the ROM again if they damage their system
- reboot button/info
- root user hint
- format for the batch file or savestate file which is safe for future releases
- great alternative to so called "debloat scripts" which are flashable via a custom recovery

I've been writing some mails with d4rken lately and he is interested in this function plus he can imagine advanced options for the pro version of SD maid.

**Comment by someone755** [comment]
This would require that either d4rken himself or some other well-versed individuals go through each phone's and each configuration's app list and try out which applications cause a change in system behavior.

I'm used to deleting things like the stock messaging and calendar applications, but I like to leave the stock (system) clock app installed. I also remove apps that I intend to install from other sources later on (i.e. most Google apps, maybe the keyboard/gallery app etc). There are quite a few applications that act like servers for system functions (like Sony's smart rotation or smart backlight, or DualShock connectivity) that users should remove based on taste and necessity. A lot of people do things differently, and saying that one configuration forced by SD Maid will make everyone happy is plain wrong.

I would, however, still like to see a way to save our actions into a SD Maid-runnable script that we could back up and use on future ROM updates etc. Since, for example, I normally always delete the same applications and system folders on both stock 4.4 and stock 6.0, and there are over 100 of those apps and half a dozen folders involved each time, saving my actions to be repeated in the future would be a great way to save some time.
