### ISSUE TITLE
SystemCleaner: Remove .odex files of nonexistent (deleted) system apps

### ISSUE THREAD

**Issue by someone755** [d4rken-org/sdmaid#923]
When manually debloating an odexed ROM, SD Maid's `AppControl` can save us quite a lot of space. `Storage analyzer` then extends those debloating possibilities into helping us find and delete unnecessary files from the system partition (e.g. OEM customization applications that, if present, get automatically installed upon a factory reset, default wallpapers, boot animations, store demo videos etc). Using this, I've consistently been able to shrink system partitions from ~1.7GB to below 1GB.

However, and I only noticed this today, the .odex files inside `/system/app` and `/system/priv-app` are left untouched. On my Xperia's stock firmware, for example, where the first thing to do after first boot is to launch SD Maid and remove anywhere from 100 to 200 system applications, this leaves quite a large batch of unneeded dex.

I don't know whether this is an issue in 5.0+, where each app and all its data (apk and odex) are stored on a per-app folder basis (i.e. a folder `/system/priv-app/[app name]/` with one apk file and one dex file). I'm currently running 4.4, hence the uncertainty, but I never noticed any leftovers when running 7.0 a mere month ago.

**Comment by d4rken** [comment]
Are you looking for the CorpseFinder to also scan `/system`?

**Comment by someone755** [comment]
If you put it that way yeah, I guess. I was thinking just /system/app and
priv-app since that's really the only place where data is left over (and
proven completely safe to delete).

**Comment by d4rken** [comment]
We basically have two approaches that require some common code. Either the corpse finder also scans `/system` or when uninstalling system apps via the AppControl tool the dex/odex/art files should be removed too. In any case we need code detecting which file belongs to which app.

Because `/system` is always a bit different on each ROM type, I was always hesistant to add something that touches `/system` as part of an automatic operation (e.g. CorpseFinder scan+delete). Changing `/system` can screw with the system and e.g. OTA updates. Theoretically though an automatic scan could make sense too because in some cases where the system app has been updated, the dex cache files on the system partition are superseeded by ones in `/data/dalvik-cache`.

Then again, without going and resizing the partition, what use is more free space on a read-only partition? If you assume that this is something that will only be done manually, AppControl could the corresponding dex/art/... files when removing a system app, and because we need ownership detection for this anways creating a corpse filter for this wouldn't be much extra work...

**Comment by someone755** [comment]
I think if we're removing system apps and care enough about the size of the partition to be willing to delete dex files, that we're aware of the possibility of breaking some system function. This could be hidden in the settings, like how scanning the system partition is done with Storage analyzer. 

Much like with the latter function, it's to reduce the partition's size on backup. A 5MB/s speed in recovery is impacted by even the smallest change in size. I can't say better than yourself how and where this should be implemented though.

**Comment by shabqty62** [comment]
سلام من چندتای از برنامه های اصلی گوشی رو پاک کردم خواهش میکنم کمکم کنید؟
