### ISSUE TITLE
Feature req: Replace "maid" animation with scrolling log

### ISSUE THREAD

**Issue by mbirth** [d4rken-org/sdmaid#983]
Instead of watching the robotic maid sipping coffee, some people wish for a more interesting entertainment while waiting for the process to finish.

https://plus.google.com/103766797578725472411/posts/HhrQ3NP1wg1

Idea 1
=====

Have a graph plot of some sort. Probably files per second over time, bytes per second ... something like this.

Idea 2
=====

A scrolling log with the progress messages. Similar to LiveBoot:

https://www.youtube.com/watch?v=N0tqzVWxpJk&t=17

In a first step, this should show the paths and actions currently going on.

In a later update ("rainy days"), actual debug log / logcat output (after it has been cleaned up) might be the way to go.

**Comment by d4rken** [comment]
Some more thoughts:

We we expect that each tool shows it's own logoutput, or would it be OK if the logoutput on each tools page is mixed? Trying to get logoutput specific to a tool is more difficult.

Maybe during rework, make sure the tags are hierchical and then filter by tag `CorpseFinder:PublicDataModule:....`. Though we won't be able to filter file operations this way because multiple tools could share file reader objects in the future, but then again those are of type `Log.VERBOSE` and are too spammy to show anyways, so maybe this isn't an issue.

**Comment by mbirth** [comment]
IMHO this should be one/the same log window for all. Also don't filter messages. If there's another process running in the background doing something, show it in the log. Perhaps even make the log a separate menu item, so you can also open it after something is done.

Also color-coding for the different verbosity-classes would be nice.

And if you want to kill some time, add options to select different fonts (probably even custom TTFs?), color schemes and font sizes. :wink:

**Comment by FlyingHorseGA** [comment]
I vote to leave well enough alone.

**Comment by JeffHorinzon** [comment]
Same as @FlyingHorseGA I too vote to leave it alone, it looks nice to have the "Maid" in SDMaid sipping her nice coffee while some transparency for us to see what's actually going on behind the scenes.
